### PR TITLE
Update contractions_dict.json

### PR DESCRIPTION
**Pull request by Empyr3an**
added another contraction for here's to here is

### CODE REVIEW

**Review by kootenpv — APPROVED** [review]
Nice, good one :)!

**Comment by kootenpv** [comment]
Result can be seen when you upgrade:

    pip install -U --no-cache contractions>=0.0.39

**Comment by Empyr3an** [comment]
weird, the refreshing didn't work so I reinstalled the package. Now when I try to import it, apparently the data folder is missing. Could you check and see if the update works for you?

**Comment by kootenpv** [comment]
@Empyr3an Thanks for letting me know, it was indeed broken.

Works for me now:

    pip install -U --no-cache contractions>=contractions-0.0.43

**Pull request merged**
